services:
  opensearch-node1:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyStr0ng@Pass123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      opensearch-node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s

  ready:
    image: alpine:latest
    container_name: people-search-ready
    depends_on:
      opensearch-node1:
        condition: service_healthy
      opensearch-dashboards:
        condition: service_healthy
    command: >
      sh -c "
      echo '========================================';
      echo '🚀 OpenSearch Stack is ready!';
      echo '========================================';
      echo '';
      echo '📊 OpenSearch API:';
      echo '   http://localhost:9200';
      echo '';
      echo '🎨 OpenSearch Dashboards:';
      echo '   http://localhost:5601';
      echo '';
      echo '========================================';
      echo 'Services are up and running ✓';
      echo '========================================'
      "

volumes:
  opensearch-data:
